# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 03:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkers_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece',
            old_name='king_Status',
            new_name='king_status',
        ),
        migrations.RemoveField(
            model_name='space',
            name='black_player',
        ),
        migrations.AlterField(
            model_name='game',
            name='red_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='space',
            name='piece_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkers_app.Piece'),
        ),
    ]
