# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkers_app', '0003_auto_20160213_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='game_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkers_app.Game'),
        ),
    ]
